name: Build & Deploy

on:
  push:
    branches:
      - main
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy project
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          
          script: |  
            mv M-F-Explorer/Explorer_server/.env tmp-env/Explorer_server
            rm -r M-F-Explorer                   
            git clone git@github.com:dstr951/M-F-Explorer.git
            mv tmp-env/Explorer_server/.env M-F-Explorer/Explorer_server
            echo 'Deployment successful'
            pkill -f go-build
            echo 'build deleted'
            pkill -f main.go
            echo 'execution deleted'
            cd M-F-Explorer/Explorer_server
            nohup go run main.go &
            cd ../../
            

            
