name: Build & Deploy

on:
  push:
    branches:
      - main
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy project
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          
          script: |  
            mv M-F-Explorer/Explorer_server/.env tmp-env/Explorer_server
            rm -r M-F-Explorer                   
            git clone git@github.com:dstr951/M-F-Explorer.git
            mv tmp-env/Explorer_server/.env M-F-Explorer/Explorer_server
            echo 'Deployment successful'
            GO_PID=$(ps aux | grep main.go | awk '{print $2}' | head -1)
            BUILD_GO_PID=$(ps aux | grep go-build | awk '{print $2}' | head -1)            
            kill $GO_PID $BUILD_GO_PID
            echo 'Killed previous server processes'            
            cd M-F-Explorer/Explorer_server
            nohup go run main.go </dev/null &>/dev/null &
            cd ../../
            exit
            

            
